[build]
target-dir = "target"

[target.'cfg(target_os = "macos")']
rustflags = [
  "-C",
  "link-arg=-Wl,-rpath,@executable_path/../Frameworks"
]

[target.'cfg(target_os = "linux")']
rustflags = [
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN"
]

[target.'cfg(target_os = "windows")']
rustflags = [
  "-C",
  "link-arg=/STACK:8388608"
]

